dist: trusty
language:
  - cpp
  - python
compiler: gcc
python: "2.7"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - g++-4.8

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.8.0/bazel_0.8.0-linux-x86_64.deb
  - sudo dpkg -i bazel_0.8.0-linux-x86_64.deb

script:
  - tools/buildall.sh
